- config/settings/local.py
It was still working, but showing lots of scary looking errors when we ran process_expired without that.
> fix(django-process_expired): add django container by name to allowed_hosts in local dev env

- scram/route_manager/api/views.py
when testing entries with curl i realized we were just using the default expiration for everything. this update actually grabs the correct expiration. 
see https://www.django-rest-framework.org/api-guide/requests/ as to why the DRF object parsing is better as well.
> fix(expiration): change to use DRF's request object parsing instead of django's

- scram/route_manager/api/views.py
- scram/route_manager/tests/acceptance/features/remove_ip.feature
- scram/route_manager/tests/test_api.py
- scram/route_manager/views.py
- setup.cfg
This restores the ability to add entries from the WUI. The logic is changed to check for either a valid client UUID or a user with the proper permissions set. 
As a side effect, there's no reason to add a web client upon initialization of the app anymore, so that bit is also removed.
> hotfix(wui): Fix broken add entry from WUI

- local.yml
- production.yml
Everything was working but the build would fail in CI. 
Fix taken from https://docs.docker.com/compose/compose-file/compose-file-v3/
Closes #15
> fix(CI): compose v3 spec doesn't like `enable_ipv6: true` so we will try the suggested fix

- production.yml
docker compose spec says this doesnt exist on v3 of the spec but it fails in production to actually get a v6 address without this
rolling back #16
> fix(v6): we DO need enable_ipv6 set to true

- scram/route_manager/api/serializers.py
- scram/route_manager/api/views.py
- scram/route_manager/tests/acceptance/steps/common.py
- scram/route_manager/tests/test_api.py
We were silently dropping the username from the json data in API calls. This meant records coming from automated tools (eg Zeek) were not attributed to anyone. This fixes that while still automatically reading the logged in user from the WUI if an entry is added that way.
Also had to update tests to use the API correctly.
> fix(Hotfix/soehlert/username): Fill out API username as well as WUI username

- .gitlab-ci.yml
- .pre-commit-config.yaml
- Makefile
- pyproject.toml
Standalone docker compose v1 we were using is deprecated. By updating the Makefile we can point to the right commands and continue to use the same Make targets in dev and via ansible deployment. Updating the .gitlab-ci.yml file to use a different image should get CI using the same version of docker compose as well.
Reordered the Makefile as well for easier understanding. Also removed an extraneous target that wasn't doing anything or working.
precommit and pyproject.toml changes were because precommit was failing not allowing any commits. These changes get it working again so we can continue committing the actual changes.
> refactor(docker compose plugin): Move to using the docker compose plugin

- .github/workflows/docs.yml
- .gitignore
- Makefile
- compose.override.local.yml
- compose.override.production.yml
- compose.yml
https://docs.docker.com/compose/multiple-compose-files/merge/
> Merge common parts of compose configs into a single file, then override as needed

- compose.override.local.yml
- compose.override.production.yml
We don't need a /48 anyways for the intracontainer network so lets just do a /64.
> fix(compose): v6 network had host bits in it

- config/consumers.py
This should make sure routes learned from another instance with a shared postgres backend get announced with the proper values set in websocketmessage dict. also fixes that for when translator gets restarted. it used to use the default asn/community in those cases
> fix(translator-consumer): make the translator consumer use websocketmessage dict

- .gitlab-ci.yml
- compose.override.production.yml
- compose.yml
This also gives the option to set an envvar to set one or more postgres containers in prod if someone wants. this allows us to keep using a separate postgres instance by default without having to manually change files on servers.
> fix(postgres_container): Don't spin up a postgres container in prod by default

- .idea/runConfigurations/Django_Debugger.xml
- .idea/runConfigurations/Translator_Debugger.xml
- .vscode/launch.json
- compose.override.local.yml
- compose.override.production.yml
- compose.yml
- config/asgi.py
- translator/translator.py
Some small cosmetic changes here are that I set the debug variable to be empty by default to supress any errors in docker compose and any unnecessary warning log. I also got rid of the version in the compose files too because that was getting really old hearing compose yell about the deprecated flag. 
This mainly though fixes the CI issues introduced by both the debugger and the postgres replica changes.  For the former, we make sure we're on a port that's not already in use by the gitlab runners, and for the latter, we ensure that for the local compose profile we default our postgres replicas for 1.
Whoopsie!
Sorry for the mix-and-match MR, can break it apart if we care.
> fix: ci issues related to recent changes

- config/settings/production.py
Django ALLOWED_HOSTS (in production) needs to be set in your SCRAM install to allow connections from the django container (for docker compose healthcheck) and the hostname of your actual server (for nginx proxied traffic, like a user hitting the WUI, API calls, etc). So for a typical SCRAM server deployed to production at `scram.example.com` you would need `ALLOWED_HOSTS` to be set to `ALLOWED_HOSTS = ["django", "scram.example.com"]`. 
This uses the `django-environ` list type casting to take the `DJANGO_ALLOWED_HOSTS` env var and set it to the correct value, for example setting the env var on the system with `export DJANGO_ALLOWED_HOSTS=django,scram.example.com` would result in this in the python settings: `ALLOWED_HOSTS = ["django", "scram.example.com"]`
> fix(settings.py): Include docker containers in django ALLOWED_HOSTS

- .github/workflows/docs.yml
This hopefully fixes our CI errors we are seeing. When we do our next release, we should double check to make sure they actually build though.
> ci(docs): only build docs on main

- Makefile
During debugging sessions we have found it really useful to be able to quickly get bgp neighbor status and information
> feat(gobgp-neighbor): add makefile target for debugging gobgp neighbors

- compose.yml
- compose/local/translator/Dockerfile
Let's move GoBGP to a recent version to reduce future suffering.
> chore(deps): bump gobgp to latest (v3.33.0)

- scram/route_manager/tests/test_authorization.py
- scram/route_manager/views.py
Closes #113 
This was an annoying UX bug where you would be on a url ending in `/add` meaning you couldn't refresh or anything since it's a POST only endpoint. This way things are still added, but now you are redirected to the actual home page.
> fix(add_form): redirect to the homepage after adding via the form on the home page

- compose.yml
- config/settings/base.py
- scram/route_manager/context_processors.py
- scram/route_manager/tests/test_performance.py
- scram/route_manager/views.py
- scram/templates/navbar.html
- scram/templates/route_manager/home.html
Closes #30
This adds a pill badge to the navbar with a quick view at active blocks. Also, it filters the homepage to only show active blocks and update the pill badge above the actiontype list on the homepage to only show the count of active blocks. The navbar is specific to blocks, but that seems fair since 1) that's the main use case right now 2) that's the only default actiontype anyways. We can always make it nicer/configurable in the future if needed.
> feat(active_blocks): Add a quick way to tell how many active blocks there are

- scram/route_manager/migrations/0032_entry_originating_scram_instance_and_more.py
This changes the default value from the placeholder to something useful.
> fix(migrations): set a proper default value for originating instance migration

- .envs/.local/.translator
- translator/gobgp.py
- translator/translator.py
It's time for the downfall of DEBUG level logging. Long live INFO level logging. To change this in translator, change the "LOGGING_LEVEL" env var for the translator container to DEBUG, INFO, etc.
> feat(translator): slap a variable on log level (and default to INFO)

- scram/route_manager/views.py
Home page entries were sorted the wrong way so you'd only see old stuff. Surprisingly annoying for troubleshooting especially since /entries/ isn't paginated yet.
> fix(homepage): sort entries properly

- scram/route_manager/tests/acceptance/environment.py
- scram/route_manager/tests/acceptance/features/query.feature
- scram/route_manager/tests/acceptance/features/search.feature
- scram/route_manager/tests/acceptance/steps/common.py
- scram/route_manager/tests/acceptance/steps/ip.py
- scram/route_manager/views.py
Closes #31 
We saw a 500 ValueError for two cases:
- a search query with extraneous whitespace
- a completely blank search query
> fix(search): Gracefully handle ValueErrors with search

- .ci-scripts/flake8_before.sh
- .github/workflows/pytest.yml
- .github/workflows/pytest_next_python.yml
- compose/local/django/Dockerfile
- compose/local/docs/Dockerfile
- compose/local/translator/Dockerfile
- compose/production/django/Dockerfile
For now, let's just use the pip compatibility layer for `uv`. 
https://docs.astral.sh/uv/pip/
> ci(build): Be like the cool kids and use `uv`

- config/settings/local.py
- config/settings/production.py
- config/settings/test.py
this lets us remove secrets from the repo (even though they are not actually a big risk)
> feat(django_secret_key): dynamically generate a django secret key if one does not exist in the environment

- scram/templates/route_manager/entry_detail.html
It just seems like bad user experience to see that. 
Closes #39
> fix(ux): only show "deactivate entry" button on the entry detail page when the entry is actually active

- .pre-commit-config.yaml
- config/settings/local.py
- scram/route_manager/views.py
- scram/shared/__init__.py
- scram/shared/shared_code.py
Django is deprecating the make_random_password() method so we need to roll our own eventually, might as well now. Also we need to change the allowed characters for the DB secret as it keeps killing the django env library.
> fix(user model): Fix default password generation.

- scram/templates/base.html
> feat(django messages): Auto close the django messages after a few seconds.
